"""empty message

Revision ID: 695307ea1c28
Revises: f6b5d9d0c53f
Create Date: 2023-02-26 18:15:08.166540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695307ea1c28'
down_revision = 'f6b5d9d0c53f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.alter_column('experience',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.alter_column('experience',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
